language: python
python:
- '2.7'
- '3.5'
sudo: required
dist: trusty
install:
- pip install yapf==0.16.0
script:
- bash devtools/travis-ci/test_format_code.sh
after_success:
- echo $TRAVIS_SECURE_ENV_VARS
- coveralls
- source devtools/travis-ci/after_sucess.sh
