language: python
python:
- '2.7'
- '3.5'
sudo: required
dist: trusty
install:
- echo "Hello World"
script:
- echo "Hello World"
after_success:
- echo $TRAVIS_SECURE_ENV_VARS
- source devtools/travis-ci/after_sucess.sh
